import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Rime of the Frostmaiden</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main} > 
        <Image src="/earth_genasi.png" width={400} height={453} />
        <div>
          <p>brimshander. First town of 10 towns located in Icewind Dale</p>
          <p>Brendan Two - Calidan (the slayer) - Human</p>
          <p>Tony - Flint Pridebreaker - Hill Dwarf</p>
          <p>Brendo - Crimnas Cenovath - Triton</p>
          <p>Will - Admiral - Hippo Man</p>
          <p>Tavern - Northlook Inn</p>
          <p>Dwarves in Tavern - Dendual, Gentrick, Noramona (Goblins stole his "product" - Have a pet bear)</p>
          <p>Yetis...</p>
          <p>The ONLY sound the gun makes is "toot toot"</p>
          <p>KBs: 4</p>
        </div>
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}

export default Home
